---
  - name: Configure the hostname of the cisco hosts
    hosts: cisco
    gather_facts: false
    become: true
    vars_files:
      - /etc/ansible/cisco/cisco.yml

    tasks:
      - name: Change the hostname based on "hostname" attribute
        cisco.ios.ios_config:
          lines:
           - hostname {{ hostname | default(inventory_hostname) }}
          save_when: "changed"
