---
  - name: Configure the loopback interfaces of the cisco hosts
    hosts: cisco
    gather_facts: false
    become: true
    vars_files:
      - /etc/ansible/cisco/cisco.yml

    tasks:
      - name: Configure the loopback with selection of corresponding info
        cisco.ios.ios_config:
          lines:
            - ip address {{ loop_net | ipaddr( groups['cisco'].index(inventory_hostname) | int + 1 ) | ipaddr('address') }} 255.255.255.255
            - description "Ansible - Routing Loopback Interface"
            - no shutdown
          parents: interface Loopback0
 
